### PR TITLE
Modify example to support read/write from/to file and factory reset

### PR DESCRIPTION
**Pull request by ajlennon**

### CODE REVIEW

**Comment by ajlennon** [comment]
Hi @Atmelfan - great library thanks! We have a new board with the stusb4500 on and needed a way to program the NVM for the PDOs we want. I took your initial example and turned it into a tool that can read/write data files to set the NVM. Hope that's useful

**Comment by Atmelfan** [comment]
Sorry for the late response. Looks very useful!

I think it'd be better to add this as a binary so it can be installed and run as a cli tool using cargo directly without bothering with examples.

I think moving your code to a new main.rs file and restoring the examples would work without any major modifications to the code.

I'm a bit busy atm but I can take a closer look next week.

[Reference](https://stackoverflow.com/questions/26946646/package-with-both-a-library-and-a-binary)

**Comment by Atmelfan** [comment]
Also I'd prefer it if it could use a format like [ihex](https://github.com/martinmroz/ihex) by default instead of anonymous binary files.

**Comment by ajlennon** [comment]
> Also I'd prefer it if it could use a format like [ihex](https://github.com/martinmroz/ihex) by default instead of anonymous binary files.

Sounds good to me. I'm in the middle of adding in some status so we can see what's actually going on now....

**Comment by ajlennon** [comment]
Was responding on the phone. Back home now. Here's where I am at to on the fork -

https://github.com/DynamicDevices/stusb4500-rs

I've been working in embedded since the mid-nineties and have had a few goes at looking at Rust but these ? marks and unwraps are breaking my brain. So what I am saying is I'm scratching an itch here and am well aware my code is probably crap so I'm not precious.

I'm working with your library (and many thanks for creating it!) because we laid down the STUSB4500 part on a new board of ours and I really like it. My colleagues need a way to program up the NVM and they want to know what the voltage and current is at any time.

https://github.com/DynamicDevices/meta-dynamicdevices/wiki/Jaguar-Sentai-Board#stusb4500

So I'm super keen to put some kind of tool together that can deal with the part  if you fancy it? I figured it was nuts there didn't seem to be a way to find out the current voltage and  the data-sheet is pretty typical of hardware engineers who don't want us software engineers to know what's going on :-D

You have register 0x21 down as reserved but I found this code which uses it to grab the current voltage

https://github.com/dotnet/iot/blob/3f2c38725a70df7cdea02f2a7f8788a46eb32f93/src/devices/StUsb4500/Enumerations/StUsb4500Register.cs#L32

I tried it and it works :) So this seems a good way forward....

I doubt I have the time - and I certainly don't have the ability - but what you've done here seems to lend itself to an exploratory driver within the Linux kernel? I'd be really interested in working with you to see if we could get this built into the kernel just to see if it's workable :-D

Anyway cheers and thanks!

**Comment by ajlennon** [comment]
ok that seems to be actually looking pretty good here! needs some rebasing maybe to tidy up ?

```
oot@imx8mm-jaguar-sentai-7130a09dab86563:/var/rootdirs/home/fio# stusb4500 status
PDO1
Fixed PDO
- higher_capability             true
- unconstrained_power           false
- usb_communications_capable    false
- dual_role_data                false
- fast_role_swap                0
- voltage                       5 V
- current                       2 A
PDO2
Fixed PDO
- higher_capability             false
- unconstrained_power           false
- usb_communications_capable    false
- dual_role_data                false
- fast_role_swap                0
- voltage                       9 V
- current                       1.5 A
PDO3
Fixed PDO
- higher_capability             false
- unconstrained_power           false
- usb_communications_capable    false
- dual_role_data                false
- fast_role_swap                0
- voltage                       12 V
- current                       1 A
Voltage 9 V
Current RDO:
- position                    2
- give_back                   false
- capability_mismatch         false
- usb_communication_capable   false
- no_usb_suspend              false
- unchunked_extended_messages false
- operating_current           1.5 A
- max_operating_currernt      3 A
```

**Comment by Atmelfan** [comment]
Hello

I refactored your program a bit and moved it into its own crate [stusb4500-utils](https://github.com/Atmelfan/stusb4500-rs/tree/main/stusb4500-utils).

Makes the install and usage a bit easier once released:
```
cargo install stusb4500-utils
stusb4500-utils --help
```

**Comment by ajlennon** [comment]
Oh that's great thanks @Atmelfan - I'll get rid of my fork then and modify my downstream Yocto recipe to use your utility :-D

https://github.com/DynamicDevices/meta-dynamicdevices/tree/main/recipes-rust/stusb4500

**Pull request merged**
