### PR TITLE
Add support for reading and writing to the NVM sectors

### PR DESCRIPTION
**Pull request by crawford**
The NVM (non-volatile memory) stores the default configuration for the
STUSB4500. Reading the sectors allows this configuration to be decoded
by the [GUI application][1].

[1]: https://www.st.com/en/embedded-software/stsw-stusb002.html

### CODE REVIEW

**Comment by Atmelfan** [comment]
Hello, thanks for the PR.

Have the code been tested on real hardware? If so, could you add an example or testbench for it?

**Comment by crawford** [comment]
Yeah, this has been tested against a custom design as well as the standard evaluation board. I added an example to show the reading and writing functionality from a Raspberry Pi.

Thanks for the library. This was a good head start on my project.

**Comment by crawford** [comment]
Sorry, I just noticed the merge conflict. Should be ready to merge now.

**Comment by Atmelfan** [comment]
This along some dependency updates have been published as v1.0.0.

**Pull request merged**
